### ISSUE TITLE
Create an article about How do I sell tickets online with eventyay?

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#9] opened 2017-01-09 11:57 UTC
Create an article about How do I sell tickets online with eventyay?

**Comment by oanarosca** [comment] 2017-01-15 14:24
Isn't this a duplicate of select payment and currency?

**Comment by mariobehling** [comment] 2017-01-15 15:05
There is always an overlap, but these are the questions people are looking for. Feel free to take some inspiration here: http://help.eventnook.com/site/article/162910100/How-do-I-sell-tickets-online-with-EventNook

**Comment by zohaayasser** [comment] 2018-11-01 10:32
Pls find the below link of how to sell tickets online 
https://codein.withgoogle.com/serve/6599694386987008/

**Closed** 2020-08-25 21:01 UTC
